// dna.js — DNA raw data import: parser, storage, context assembly
// Parses raw DNA files from Ancestry, 23andMe, MyHeritage, FTDNA, Living DNA
// Runs the heavy parsing in a Web Worker (inline blob) to keep UI responsive

import { state } from './state.js';
import { escapeHTML, showNotification } from './utils.js';

// ═══════════════════════════════════════════════
// FORMAT DETECTION
// ═══════════════════════════════════════════════

// Detect DNA file by checking first few lines of text content
export function detectDNAFile(text) {
  const first = text.slice(0, 500);
  if (first.startsWith('#AncestryDNA')) return 'ancestry';
  if (first.includes('# This data file generated by 23andMe')) return '23andme';
  if (first.includes('# Living DNA customer genotype data download file version')) return 'livingdna';
  // CSV formats — no comment lines, start with header
  const firstLine = first.split(/\r?\n/)[0].trim();
  if (/^RSID,CHROMOSOME,POSITION,RESULT$/i.test(firstLine)) return 'csv'; // MyHeritage or FTDNA
  if (/^"?RSID"?,/i.test(firstLine)) return 'csv'; // quoted variant
  return null;
}

// Check if a dropped/selected file looks like a DNA raw data file
export function isDNAFile(file) {
  if (!file) return false;
  const name = file.name.toLowerCase();
  // Common DNA file patterns
  if (name.includes('ancestrydna')) return true;
  if (name.includes('23andme')) return true;
  if (name.includes('myheritage') && name.includes('dna')) return true;
  if (name.includes('family_finder')) return true;
  if (name.includes('livingdna') || name.includes('living_dna')) return true;
  return false;
}

// ═══════════════════════════════════════════════
// WEB WORKER PARSER (inline blob)
// ═══════════════════════════════════════════════

const WORKER_CODE = `
// DNA parser worker — receives { file, snpIds, format }
// Posts back { matches, source, totalLines, format }

self.onmessage = async function(e) {
  const { file, snpIds, format } = e.data;
  const text = await file.text();
  const lines = text.split(/\\r?\\n/);
  const lookupSet = new Set(snpIds);
  const matches = {};
  let totalData = 0;
  let detectedFormat = format;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line || line.startsWith('#')) continue;

    // Skip header lines
    const upper = line.toUpperCase();
    if (upper.startsWith('RSID') || upper.startsWith('"RSID')) continue;

    let rsid, genotype;

    if (detectedFormat === 'ancestry') {
      // Tab-separated: rsid, chromosome, position, allele1, allele2
      const parts = line.split('\\t');
      if (parts.length < 5) continue;
      rsid = parts[0].trim();
      const a1 = parts[3].trim();
      const a2 = parts[4].trim();
      if (a1 === '0' || a2 === '0' || a1 === '-' || a2 === '-') { totalData++; continue; }
      genotype = a1 + a2;
    } else if (detectedFormat === '23andme' || detectedFormat === 'livingdna') {
      // Tab-separated: rsid, chromosome, position, genotype
      const parts = line.split('\\t');
      if (parts.length < 4) continue;
      rsid = parts[0].trim();
      genotype = parts[3].trim();
      if (genotype === '--' || genotype === '00') { totalData++; continue; }
    } else if (detectedFormat === 'csv') {
      // Comma-separated: RSID, CHROMOSOME, POSITION, RESULT (possibly quoted)
      const parts = line.split(',').map(s => s.replace(/^"|"$/g, '').trim());
      if (parts.length < 4) continue;
      rsid = parts[0];
      genotype = parts[3];
      if (genotype === '--' || genotype === '00' || !genotype) { totalData++; continue; }
    } else {
      continue;
    }

    // Skip internal IDs (23andMe uses i-prefixed IDs for some markers)
    if (!rsid.startsWith('rs')) { totalData++; continue; }

    totalData++;

    if (lookupSet.has(rsid)) {
      matches[rsid] = genotype;
    }
  }

  self.postMessage({ matches, source: detectedFormat, totalLines: totalData, format: detectedFormat });
};
`;

let _worker = null;

function getWorker() {
  if (!_worker) {
    const blob = new Blob([WORKER_CODE], { type: 'application/javascript' });
    _worker = new Worker(URL.createObjectURL(blob));
  }
  return _worker;
}

// ═══════════════════════════════════════════════
// PARSE DNA FILE
// ═══════════════════════════════════════════════

let _snpTable = null;

async function loadSNPTable() {
  if (_snpTable) return _snpTable;
  const resp = await fetch('data/snp-health.json');
  _snpTable = await resp.json();
  return _snpTable;
}

// Returns { matches: { rsid: { genotype, gene, variant, effect, note } }, source, totalLines, coverage }
export async function parseDNAFile(file) {
  const snpTable = await loadSNPTable();
  const snpIds = Object.keys(snpTable).filter(k => k.startsWith('rs'));

  // Detect format from first chunk
  const headerChunk = await file.slice(0, 1000).text();
  const format = detectDNAFile(headerChunk);
  if (!format) throw new Error('Unrecognized DNA file format');

  // Run parser in worker
  const worker = getWorker();
  const result = await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('DNA parsing timed out')), 30000);
    worker.onmessage = (e) => { clearTimeout(timeout); resolve(e.data); };
    worker.onerror = (e) => { clearTimeout(timeout); reject(new Error(e.message)); };
    worker.postMessage({ file, snpIds, format });
  });

  // Enrich matches with lookup table data
  const enriched = {};
  for (const [rsid, genotype] of Object.entries(result.matches)) {
    const entry = snpTable[rsid];
    if (!entry) continue;
    const reversed = genotype.length === 2 ? genotype[1] + genotype[0] : genotype;
    const genotypeInfo = entry.genotypes[genotype] || entry.genotypes[reversed] || entry.genotypes[sortAlleles(genotype)] || null;
    enriched[rsid] = {
      genotype,
      gene: entry.gene,
      variant: entry.variant,
      category: entry.category,
      markers: entry.markers || [],
      effect: genotypeInfo ? genotypeInfo.effect : 'unknown',
      note: genotypeInfo ? genotypeInfo.note : `Genotype ${genotype} not in lookup table`,
    };
  }

  return {
    matches: enriched,
    source: formatSourceName(result.source),
    totalLines: result.totalLines,
    coverage: { found: Object.keys(enriched).length, total: snpIds.length },
  };
}

// Sort alleles alphabetically for lookup (AG = GA)
function sortAlleles(genotype) {
  if (!genotype || genotype.length !== 2) return genotype;
  const sorted = genotype.split('').sort().join('');
  return sorted;
}

function formatSourceName(format) {
  const names = { ancestry: 'AncestryDNA', '23andme': '23andMe', livingdna: 'Living DNA', csv: 'MyHeritage/FTDNA' };
  return names[format] || format;
}

// ═══════════════════════════════════════════════
// APOE HAPLOTYPE RESOLUTION
// ═══════════════════════════════════════════════

// APOE is determined by two SNPs: rs429358 and rs7412
// rs429358 T→C = ε4 allele, rs7412 C→T = ε2 allele
function resolveAPOE(matches) {
  const rs429358 = matches.rs429358?.genotype;
  const rs7412 = matches.rs7412?.genotype;
  if (!rs429358 || !rs7412) return null;

  // Determine alleles from the two SNPs
  function getAllele(rs429358_allele, rs7412_allele) {
    if (rs429358_allele === 'T' && rs7412_allele === 'C') return 'ε2';
    if (rs429358_allele === 'T' && rs7412_allele === 'T') return 'ε3';
    if (rs429358_allele === 'C' && rs7412_allele === 'T') return 'ε4';
    return null;
  }

  const a1 = getAllele(rs429358[0], rs7412[0]);
  const a2 = getAllele(rs429358[1], rs7412[1]);
  if (!a1 || !a2) return null;

  // Sort for consistent display (ε2/ε3, not ε3/ε2)
  const sorted = [a1, a2].sort();
  return sorted.join('/');
}

// ═══════════════════════════════════════════════
// STORAGE
// ═══════════════════════════════════════════════

export function saveGeneticsData(profileData, parseResult) {
  profileData.genetics = {
    source: parseResult.source,
    importDate: new Date().toISOString().slice(0, 10),
    coverage: parseResult.coverage,
    snps: {},
  };
  for (const [rsid, data] of Object.entries(parseResult.matches)) {
    profileData.genetics.snps[rsid] = {
      genotype: data.genotype,
      gene: data.gene,
      variant: data.variant,
    };
  }
  // Resolve APOE haplotype
  const apoe = resolveAPOE(parseResult.matches);
  if (apoe) {
    profileData.genetics.apoe = apoe;
  }
}

export function deleteGeneticsData(profileData) {
  delete profileData.genetics;
}

// ═══════════════════════════════════════════════
// CONTEXT ASSEMBLY
// ═══════════════════════════════════════════════

// Build genetics context string for AI — only non-"none" effects, relevant to current markers
export function buildGeneticsContext(genetics, activeMarkerKeys) {
  if (!genetics || !genetics.snps) return '';
  const snpTable = _snpTable; // already loaded by parseDNAFile or loadSNPTable
  if (!snpTable) return '';

  const lines = [];

  // APOE haplotype — always include
  if (genetics.apoe) {
    lines.push(`APOE: ${genetics.apoe}`);
  }

  // Group SNPs by category — skip raw APOE component SNPs (haplotype shown instead)
  const apoeRsids = new Set(['rs429358', 'rs7412']);
  const byCategory = {};
  for (const [rsid, stored] of Object.entries(genetics.snps)) {
    if (genetics.apoe && apoeRsids.has(rsid)) continue; // haplotype covers these
    const entry = snpTable[rsid];
    if (!entry) continue;
    const reversed = stored.genotype.length === 2 ? stored.genotype[1] + stored.genotype[0] : stored.genotype;
    const genotypeInfo = entry.genotypes[stored.genotype] || entry.genotypes[reversed] || entry.genotypes[sortAlleles(stored.genotype)];
    if (!genotypeInfo || genotypeInfo.effect === 'none') continue;

    // Filter to SNPs relevant to active markers (if provided)
    if (activeMarkerKeys && activeMarkerKeys.length > 0) {
      const hasRelevantMarker = (entry.markers || []).some(m => activeMarkerKeys.includes(m));
      if (!hasRelevantMarker) continue;
    }

    const cat = entry.category || 'other';
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat].push(`${stored.gene} ${stored.variant}: ${stored.genotype} — ${genotypeInfo.note}`);
  }

  for (const [cat, entries] of Object.entries(byCategory)) {
    lines.push(...entries);
  }

  if (lines.length === 0) return '';
  return `GENETICS (${genetics.source}, ${Object.keys(genetics.snps).length} SNPs):\n${lines.map(l => '- ' + l).join('\n')}`;
}

// Full genetics dump for when user explicitly asks about genetics
export function buildFullGeneticsContext(genetics) {
  return buildGeneticsContext(genetics, null); // no marker filter = include all non-none
}

// ═══════════════════════════════════════════════
// DASHBOARD SECTION
// ═══════════════════════════════════════════════

export function renderGeneticsSection() {
  const genetics = state.importedData.genetics;
  if (!genetics || !genetics.snps || Object.keys(genetics.snps).length === 0) return '';
  const snpTable = _snpTable;

  const snpCount = Object.keys(genetics.snps).length;
  const apoe = genetics.apoe;

  // Group significant/moderate findings for summary
  const findings = [];
  const apoeRsids = new Set(['rs429358', 'rs7412']);
  for (const [rsid, stored] of Object.entries(genetics.snps)) {
    if (apoe && apoeRsids.has(rsid)) continue;
    const entry = snpTable?.[rsid];
    if (!entry) continue;
    const reversed = stored.genotype.length === 2 ? stored.genotype[1] + stored.genotype[0] : stored.genotype;
    const info = entry.genotypes[stored.genotype] || entry.genotypes[reversed] || entry.genotypes[sortAlleles(stored.genotype)];
    if (!info || info.effect === 'none') continue;
    findings.push({ gene: stored.gene, variant: stored.variant, genotype: stored.genotype, effect: info.effect, note: info.note });
  }

  const effectIcon = { significant: '\uD83D\uDD34', moderate: '\uD83D\uDFE1' };

  let html = `<div class="dashboard-section genetics-section">
    <div class="section-header">
      <span>\uD83E\uDDEC Genetics</span>
      <span class="section-meta">${escapeHTML(genetics.source)} · ${snpCount} SNPs · ${genetics.importDate}</span>
    </div>`;

  if (apoe) {
    html += `<div class="genetics-apoe">APOE: <strong>${escapeHTML(apoe)}</strong></div>`;
  }

  if (findings.length > 0) {
    html += `<div class="genetics-findings">`;
    // Show significant first, then moderate
    const sorted = findings.sort((a, b) => (a.effect === 'significant' ? 0 : 1) - (b.effect === 'significant' ? 0 : 1));
    for (const f of sorted.slice(0, 8)) {
      html += `<div class="genetics-finding-row">
        <span>${effectIcon[f.effect] || ''}</span>
        <span class="genetics-finding-gene">${escapeHTML(f.gene)} ${escapeHTML(f.variant)}</span>
        <span class="genetics-finding-genotype">${escapeHTML(f.genotype)}</span>
        <span class="genetics-finding-note">${escapeHTML(f.note)}</span>
      </div>`;
    }
    if (sorted.length > 8) {
      html += `<div class="genetics-finding-more">${sorted.length - 8} more findings</div>`;
    }
    html += `</div>`;
  }

  html += `<div class="genetics-actions">
    <button class="import-btn import-btn-secondary" style="font-size:11px;padding:3px 10px" onclick="if(confirm('Delete genetic data?')){deleteGeneticsData(window._getState().importedData);window._saveAndRefresh();}">\u00D7 Delete</button>
  </div></div>`;

  return html;
}

// ═══════════════════════════════════════════════
// IMPORT FLOW
// ═══════════════════════════════════════════════

import { saveImportedData } from './data.js';

export async function handleDNAFile(file) {
  try {
    showNotification('Parsing DNA file...', 'info');
    const result = await parseDNAFile(file);
    if (Object.keys(result.matches).length === 0) {
      showNotification('No health-relevant SNPs found in this file. Is it a DNA raw data export?', 'error');
      return;
    }
    showDNAImportPreview(result, file.name);
  } catch (e) {
    console.error('DNA import error:', e);
    showNotification(e.message || 'Failed to parse DNA file', 'error');
  }
}

function showDNAImportPreview(result, fileName) {
  window._pendingDNAImport = result;

  // Categorize matches by effect — skip raw APOE components when haplotype resolved
  const apoe = resolveAPOE(result.matches);
  const apoeRsids = apoe ? new Set(['rs429358', 'rs7412']) : new Set();
  const significant = [], moderate = [], none = [], unknown = [];
  for (const [rsid, m] of Object.entries(result.matches)) {
    if (apoeRsids.has(rsid)) continue;
    const item = { rsid, ...m };
    if (m.effect === 'significant') significant.push(item);
    else if (m.effect === 'moderate') moderate.push(item);
    else if (m.effect === 'none') none.push(item);
    else unknown.push(item);
  }

  const effectIcon = { significant: '\uD83D\uDD34', moderate: '\uD83D\uDFE1', none: '\uD83D\uDFE2', unknown: '\u2753' };
  const effectLabel = { significant: 'Significant impact', moderate: 'Moderate impact', none: 'Normal / no impact', unknown: 'Not in lookup' };

  function renderGroup(items, label) {
    if (items.length === 0) return '';
    return `<div class="dna-preview-group">
      <div class="dna-preview-group-title">${label} (${items.length})</div>
      ${items.map(m => `<div class="dna-preview-row">
        <span class="dna-preview-icon">${effectIcon[m.effect] || '\u2753'}</span>
        <span class="dna-preview-gene">${escapeHTML(m.gene)} ${escapeHTML(m.variant)}</span>
        <span class="dna-preview-genotype">${escapeHTML(m.genotype)}</span>
        <span class="dna-preview-note">${escapeHTML(m.note)}</span>
      </div>`).join('')}
    </div>`;
  }

  const html = `
    <div class="dna-preview-header">
      <div class="dna-preview-title">DNA Import — ${escapeHTML(result.source)}</div>
      <div class="dna-preview-stats">${result.totalLines.toLocaleString()} SNPs scanned · ${result.coverage.found} of ${result.coverage.total} health-relevant SNPs found</div>
      ${apoe ? `<div class="dna-preview-apoe">APOE Haplotype: <strong>${escapeHTML(apoe)}</strong></div>` : ''}
    </div>
    <div class="dna-preview-body">
      ${renderGroup(significant, '\uD83D\uDD34 Significant findings')}
      ${renderGroup(moderate, '\uD83D\uDFE1 Moderate findings')}
      ${renderGroup(none, '\uD83D\uDFE2 Normal')}
      ${renderGroup(unknown, '\u2753 Genotype not in lookup')}
    </div>
    <div class="dna-preview-disclaimer">
      Your DNA file was processed locally and never transmitted. Only matched health-relevant SNPs are stored.
      Genetic information is for educational context alongside your lab results — not a medical diagnosis.
    </div>
    <div class="dna-preview-actions">
      <button class="import-btn import-btn-secondary" onclick="closeDNAImportPreview()">Cancel</button>
      <button class="import-btn import-btn-primary" onclick="confirmDNAImport()">Import ${result.coverage.found} SNPs</button>
    </div>`;

  // Use the existing import modal overlay
  let overlay = document.getElementById('import-modal-overlay');
  if (!overlay) {
    overlay = document.createElement('div');
    overlay.id = 'import-modal-overlay';
    overlay.className = 'modal-overlay';
    document.body.appendChild(overlay);
  }
  overlay.innerHTML = `<div class="modal dna-preview-modal" role="dialog">${html}</div>`;
  overlay.classList.add('show');
}

function closeDNAImportPreview() {
  window._pendingDNAImport = null;
  const overlay = document.getElementById('import-modal-overlay');
  if (overlay) overlay.classList.remove('show');
}

function confirmDNAImport() {
  const result = window._pendingDNAImport;
  if (!result) return;
  saveGeneticsData(state.importedData, result);
  saveImportedData();
  window._pendingDNAImport = null;
  const overlay = document.getElementById('import-modal-overlay');
  if (overlay) overlay.classList.remove('show');
  showNotification(`Imported ${result.coverage.found} SNPs from ${result.source}`, 'success');
  // Refresh dashboard
  if (window.navigate) window.navigate('dashboard');
}

// ═══════════════════════════════════════════════
// DETAIL MODAL HELPER
// ═══════════════════════════════════════════════

// Get SNPs relevant to a specific marker dotKey (e.g. "coagulation.homocysteine")
function getRelevantSNPs(dotKey) {
  const genetics = state.importedData.genetics;
  if (!genetics || !genetics.snps || !_snpTable) return [];
  const results = [];
  const apoeRsids = new Set(['rs429358', 'rs7412']);
  for (const [rsid, stored] of Object.entries(genetics.snps)) {
    if (genetics.apoe && apoeRsids.has(rsid)) continue;
    const entry = _snpTable[rsid];
    if (!entry || !entry.markers) continue;
    if (!entry.markers.includes(dotKey)) continue;
    const reversed = stored.genotype.length === 2 ? stored.genotype[1] + stored.genotype[0] : stored.genotype;
    const info = entry.genotypes[stored.genotype] || entry.genotypes[reversed] || entry.genotypes[sortAlleles(stored.genotype)];
    if (!info) continue;
    results.push({ gene: stored.gene, variant: stored.variant, genotype: stored.genotype, effect: info.effect, note: info.note });
  }
  return results;
}

// ═══════════════════════════════════════════════
// WINDOW EXPORTS
// ═══════════════════════════════════════════════
Object.assign(window, {
  isDNAFile,
  handleDNAFile,
  closeDNAImportPreview,
  confirmDNAImport,
  deleteGeneticsData,
  _buildGeneticsContext: buildGeneticsContext,
  _getRelevantSNPs: getRelevantSNPs,
  _getState: () => state,
  _saveAndRefresh: () => { saveImportedData(); if (window.navigate) window.navigate('dashboard'); },
});
